### PR TITLE
Fix lifetime parameter

### PR DESCRIPTION
**Pull request by miterst**
When trying to compile with rust-1.45.0(also 1.44.0) I was getting the following error:
```rust
error[E0726]: implicit elided lifetime not allowed here
   --> src/adapter.rs:187:68
    |
187 |     async fn load_filtered_policy(&mut self, m: &mut dyn Model, f: Filter) -> Result<()> {
    |                                                                    ^^^^^^- help: indicate the anonymous lifetime: `<'_>`
```

Adding the lifetime parameter explicitly resolves the problem.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@GopherJ @hackerchai @PsiACE

**Comment by hackerchai** [comment]
> When trying to compile with rust-1.45.0(also 1.44.0) I was getting the following error:
> ```rust
> error[E0726]: implicit elided lifetime not allowed here
>    --> src/adapter.rs:187:68
>     |
> 187 |     async fn load_filtered_policy(&mut self, m: &mut dyn Model, f: Filter) -> Result<()> {
>     |                                                                    ^^^^^^- help: indicate the anonymous lifetime: `<'_>`
> ```
> 
> Adding the lifetime parameter explicitly resolves the problem.
> 

@miterst  Please fix the CI error.
